/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,svelte,ts}"],
  theme: {
    extend: {
      colors: {
        dark: {
          primary: "#aac7ff",
          onPrimary: "#0a305f",
          secondary: "#bec6dc",
          onSecondary: "#283141",
          tertiary: "#ddbce0",
          onTertiary: "#3f2844",
          error: "#ffb4ab",
          onError: "#690005",
          primaryContainer: "#284777",
          onPrimaryContainer: "#d6e3ff",
          secondaryContainer: "#3e4759",
          onSecondaryContainer: "#dae2f9",
          tertiaryContainer: "#573e5c",
          onTertiaryContainer: "#fad8fd",
          errorContainer: "#93000a",
          onErrorContainer: "#ffdad6",
          surface: "#111318",
          onSurface: "#e2e2e9",
          onSurfaceVarient: "#c4c6d0",
          surfaceBright: "#37393e",
          surfaceContainerLowest: "#0c0e13",
          surfaceContainerLow: "#191c20",
          surfaceContainer: "#1d2024",
          surfaceContainerHigh: "#282a2f",
          surfaceContainerHighest: "#33353a",
          outline: "#8e9099",
          outlineVarient: "#44474e",
        },
        light: {
          primary: "#aac7ff",
          onPrimary: "#0a305f",
          secondary: "#bec6dc",
          onSecondary: "#283141",
          tertiary: "#ddbce0",
          onTertiary: "#3f2844",
          error: "#ffb4ab",
          onError: "#690005",
          primaryContainer: "#284777",
          onPrimaryContainer: "#d6e3ff",
          secondaryContainer: "#3e4759",
          onSecondaryContainer: "#dae2f9",
          tertiaryContainer: "#573e5c",
          onTertiaryContainer: "#fad8fd",
          errorContainer: "#93000a",
          onErrorContainer: "#ffdad6",
          surface: "#f9f9ff",
          onSurface: "#191c20",
          onSurfaceVarient: "#44474e",
          surfaceDim: "#d9d9e0",
          surfaceContainerLowest: "#ffffff",
          surfaceContainerLow: "#f3f3fa",
          surfaceContainer: "#ededf4",
          surfaceContainerHigh: "#e7e8ee",
          surfaceContainerHighest: "#e2e2e9",
          outline: "#74777f",
          outlineVarient: "#c4c6d0",
        },
      },
    },
  },
  plugins: [],
};
