// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetPublicIP() {
  return window['go']['main']['App']['GetPublicIP']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function StopTrace() {
  return window['go']['main']['App']['StopTrace']();
}

export function Trace(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Trace'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
