// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';
import {layers} from '../models';
import {pcap} from '../models';

export function CreateIPV4EthernetFrame(arg1:net.HardwareAddr,arg2:net.HardwareAddr):Promise<layers.Ethernet>;

export function CreateIPV4Packet(arg1:number,arg2:number,arg3:layers.IPProtocol,arg4:net.IP,arg5:net.IP):Promise<layers.IPv4>;

export function CreateTCPSYNPacket(arg1:number,arg2:number,arg3:number,arg4:number,arg5:layers.IPv4):Promise<layers.TCP>;

export function FindGoInterfaceByFromPcapInterface(arg1:pcap.Interface,arg2:Array<net.Interface>):Promise<net.Interface>;

export function FindInterfaceIPV4Address(arg1:net.Interface,arg2:string):Promise<net.IP>;

export function GetInterfaces():Promise<Array<any>>;

export function GetPublicIP():Promise<string>;

export function GetVersion():Promise<string>;

export function Log(arg1:string):Promise<void>;

export function SendArpRequest(arg1:pcap.Handle,arg2:net.Interface,arg3:net.IP,arg4:net.IP):Promise<net.HardwareAddr>;

export function StopTrace():Promise<void>;

export function Trace(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:number,arg7:number):Promise<string>;
