// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInterfaces():Promise<Array<any>>;

export function GetPublicIP():Promise<string>;

export function GetVersion():Promise<string>;

export function StopTrace():Promise<void>;

export function Trace(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:number,arg7:number):Promise<string>;
