// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateIPV4EthernetFrame(arg1, arg2) {
  return window['go']['main']['App']['CreateIPV4EthernetFrame'](arg1, arg2);
}

export function CreateIPV4Packet(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateIPV4Packet'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTCPSYNPacket(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTCPSYNPacket'](arg1, arg2, arg3, arg4, arg5);
}

export function FindGoInterfaceByFromPcapInterface(arg1, arg2) {
  return window['go']['main']['App']['FindGoInterfaceByFromPcapInterface'](arg1, arg2);
}

export function FindInterfaceIPV4Address(arg1, arg2) {
  return window['go']['main']['App']['FindInterfaceIPV4Address'](arg1, arg2);
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetPublicIP() {
  return window['go']['main']['App']['GetPublicIP']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function SendArpRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendArpRequest'](arg1, arg2, arg3, arg4);
}

export function StopTrace() {
  return window['go']['main']['App']['StopTrace']();
}

export function Trace(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['Trace'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
